apiVersion: v2
appVersion: "9.0.0"
description: A Helm chart for Kubernetes
name: alerta-web
version: 0.1.5
home: https://github.com/hayk96/alerta-web
icon: https://raw.githubusercontent.com/hayk96/alerta-web/main/logo/mstile-310x310.png
dependencies:
  - name: postgresql
    version: "12.2.3"
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
sources:
  - https://github.com/alerta/alerta
  - https://github.com/alerta/alerta-webui
maintainers:
  - name: Hayk Davtyan
    url: https://github.com/hayk96
keywords:
  - monitoring
  - alerting
